"before_install": [
    "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -",
    "echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" | sudo tee -a /etc/apt/sources.list",
    "sudo apt-get update -qq",
    "sudo apt-get install -y google-chrome-stable",
#    "wget 'https://download.mozilla.org/?product=firefox-beta-latest&lang=en-US&os=linux64' -O firefox-beta.tar.bz2 && tar xvjf firefox-beta.tar.bz2"
  ],
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
language: java
jdk:
  - oraclejdk8
script:
  - gradle assemble
  - gradle check --debug
cache:
  directories:
  - $HOME/.m2
addons:
  firefox: "49.0"
